### ISSUE TITLE
Several more hashes and benchmarks

### ISSUE THREAD

**Issue by KirillOsenkov** [TommasoBelluzzo/FastHashes#6]
Nice project! 

I have several string hash benchmarks and tests here, if you're interested (Marvin, djb2, Fnv-1a, etc):
https://github.com/KirillOsenkov/Benchmarks/tree/main/src/Tests

Benchmark results here:
https://github.com/KirillOsenkov/Benchmarks/blob/516b5bde9bd7bdc59a9fdd5b6436b26480d7d795/src/Tests/StringHash.cs#L12-L25

**Comment by TommasoBelluzzo** [comment]
Thank you for your contribution, I'll try to integrate all this into the project when I have some spare time.
If you want to provide help to some extent, you are more than welcome.

Tommaso

**Comment by TommasoBelluzzo** [comment]
Hi @KirillOsenkov, most of those missing hash functions can't pass some of the core quality tests.
But stay tuned as I'm going to implement some more hashes in the upcoming release.

Tommaso
