### ISSUE TITLE
s_AllowsUnalignedRead causing inconsistent hash results in .NET 4.0

### ISSUE THREAD

**Issue by EliDll** [TommasoBelluzzo/FastHashes#7]
NOTE: This is probably a very niche problem since I needed to compile the source myself to get it to work with an existing .NET 4.0 project.

If the source code as is is used in .NET 4.0, I've encountered in my unit tests that the produced hash value alternates between different executions. Since it alternates between two values i suspect the problem has something to do with wrong memory alignment. This happens when compiling for "Any CPU" and executing on a 64bit OS.

Always setting the s_AllowsUnalignedRead  flag in the Hash class to true seemed to fix this error. Am I correct in the understanding that if the s_AllowsUnalignedRead flag is set to **true** you allow **less optimization**?

For my application this change did not affect performance in any significant way so I might just keep it at that, but I would appreciate any insight you might have on this issue.

Best,
Elias

**Comment by TommasoBelluzzo** [comment]
Hi @EliDll, thanks for your precious feedback. This was an experimental optimization that I never removed from the code, but the suspect it brings no added value to the overall performance is high, and the drawback is having unit test failures in certain contexts. I'm gonna remove it soon.

**Comment by TommasoBelluzzo** [comment]
A new version is available and this issue should be finally fixed.

Tommaso
