### ISSUE TITLE
FarmHash128 throws IndexOutOfRangeException when input size is exactly 16

### ISSUE THREAD

**Issue by Schnutzel** [TommasoBelluzzo/FastHashes#9]
If input length is exactly 16 bytes then FarmHash128.ComputeHash throws an IndexOutOfRangeException .

## Expected Behavior
Function should work.

## Current Behavior
Exception is thrown:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at FastHashes.FarmHash128.Hash1To3(UInt64& hash1, UInt64& hash2, ReadOnlySpan`1 buffer, Int32 offset, Int32 count, UInt64 seed1, UInt64 seed2)
   at FastHashes.FarmHash128.ComputeHashInternal(ReadOnlySpan`1 buffer)
   at FastHashes.Hash.ComputeHash(Byte[] buffer, Int32 offset, Int32 count)
   at FastHashes.Hash.ComputeHash(Byte[] buffer)
```

## Steps to Reproduce
```
byte[] input = new byte[16];
FarmHash128 fh = new FarmHash128();
fh.ComputeHash(input);
```

## Note
An exception is also thrown when input size is 0.

**Comment by TommasoBelluzzo** [comment]
Thanks for the feedback. Gonna tackle this asap!

**Comment by TommasoBelluzzo** [comment]
Hi @Schnutzel, I tried to reproduce this bug but I couldn't.
I added a new unit test to help me spot this kind of errors but I never hit an assert in your specific case.
On the other hand, it detected another missbehavior on zero-length buffers which I'm going to fix anyway.

May I kindly know which library version you are currently using?

```
[Theory]
[MemberData(nameof(HashTestsCases.DataLength), MemberType = typeof(HashTestsCases))]
public void LengthTest(String hashName, Func<UInt32, Hash> hashInitializer, Int32 maximumLength)
{
    UInt32 seed = (UInt32)((new Random()).Next());
    Hash hash = hashInitializer(seed);
    RandomXorShift random = new RandomXorShift(seed);

    List<String> errorLengths = new List<String>();

    for (Int32 i = 0; i <= maximumLength; ++i)
    {
        Byte[] buffer = new Byte[i];
        random.NextBytes(buffer);

        try
        {
            hash.ComputeHash(buffer);
        }
        catch
        {
            errorLengths.Add(i.ToString());
        }
    }

    m_Output.WriteLine($"NAME: {hashName}");

    if (errorLengths.Count > 0)
        m_Output.WriteLine($"ERROR LENGTHS: {String.Join(", ", errorLengths)}");
    else
        m_Output.WriteLine("NO ERROR LENGTHS");

    Assert.True(errorLengths.Count == 0);
}
```

**Comment by Schnutzel** [comment]
Thanks for the quick reply!

I tried this again right now, both with version 3.3.0 and 3.4.0. Same problem. This is my code:
```
        static void Main(string[] args)
        {
            Random rand = new Random();
            for (int i = 0; i < 1000; i++)
            {
                try
                {
                    byte[] input = new byte[i];
                    rand.NextBytes(input);
                    FarmHash128 fh = new FarmHash128();
                    fh.ComputeHash(input);
                }
                catch (Exception e)
                {
                    Console.WriteLine($"Exception for {i}");
                    Console.WriteLine(e);
                }
            }
        }
```

This was the result for 3.4.0:
```
Exception for 16
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.ThrowHelper.ThrowIndexOutOfRangeException()
   at FastHashes.FarmHash128.ComputeHashInternal(ReadOnlySpan`1 buffer)
   at FastHashes.Hash.ComputeHash(Byte[] buffer, Int32 offset, Int32 count)
   at ConsoleApp2.Program.Main(String[] args)
```

I am using .NET Framework 4.8 on Windows 10.

**Comment by TommasoBelluzzo** [comment]
Hi @Schnutzel

NET Framework, I see... I think this might be an important hint.
I always tested my code against Core/Standard environments.

The strangest part is the stack trace, which does not specify in which part of the code the exception is being thrown. The calls sequence should be:

```
FastHashes.FarmHash128.ComputeHashInternal
FastHashes.FarmHash128.Hash8To16
```

Then, one of the calls to **BinaryOperations.Read64** must be throwing the exception for some reason I can't understand. Maybe the exception is thrown by **ReadOnlySpan<Byte>.Slice** or by **BinaryPrimitives.ReadUInt64LittleEndian**.

Are you able to debug the code and step into **FastHashes** to see what's going on?
Otherwise I'll try to tackle this in the upcoming days by replicating the code under .NET Framework.

**Comment by Schnutzel** [comment]
Hi @TommasoBelluzzo,

The same problem happened in .NET 5.
The exception is thrown in Hash1to3, because offset=16 but the buffer is exactly 16 bytes long.
I just noticed the difference between my code and yours - in your code you use a random seed, while I just use the default constructor. When I use a random seed, the code works.
Is there a problem with using the default constructor?

**Comment by TommasoBelluzzo** [comment]
@Schnutzel nice catch, let me try!

**Comment by TommasoBelluzzo** [comment]
@Schnutzel fix version published
